---
extends:
  - stylelint-config-recommended
  - stylelint-config-idiomatic-order
plugins:
  - stylelint-prettier
  - stylelint-declaration-block-no-ignored-properties
  - stylelint-high-performance-animation
  - stylelint-no-unsupported-browser-features
  - stylelint-use-logical
  - stylelint-value-no-unknown-custom-properties
rules:
  plugin/declaration-block-no-ignored-properties: true
  plugin/no-low-performance-animation-properties: true
  plugin/no-unsupported-browser-features:
    - true
    - severity: warning
  csstools/use-logical: true
  csstools/value-no-unknown-custom-properties: true
  prettier/prettier: true
